[project]  
name = "persistenciatrabalho2"  
version = "0.1.0"  
description = "API para gerenciamento de medicamentos"  
readme = "README.md"  
requires-python = ">=3.12"  

dependencies = [
    "fastapi[standard]",
    "sqlmodel",
    "uvicorn",
    "python-dotenv",
    "pydantic>=2.10.4",
]
